### ISSUE TITLE
Request for Schema validation

### ISSUE THREAD

**Issue by gk-hpe** [Redocly/openapi-cli#570] opened 2022-02-23 06:41 UTC
**Is your feature request related to a problem? Please describe.**
No - This is not related to any problems.

It seems like currently, we don't have any schema validation for request parameters. I think it would be great if you could add a schema evaluation like the online swagger editor.

**Describe the solution you'd like**

If we do not have a scheme for the request parameters, I think we can raise an error as shown below. 

![image](https://user-images.githubusercontent.com/86403210/155270781-f238c10d-49bc-4d3b-9a07-d149c820660f.png)

**OpenAPI Specification**

```yaml
openapi: 3.0.0
info:
  title: Petstore API
  version: 1.0.0
  description: description

paths:

  /v1/pets/{petId}:
    get:
      tags:
        - pets
      summary: Gets a specific pet
      parameters:
      - name: petId
        in: path
      - name: limit
        in: query
      responses:
        '200':
          description: Details of the requested pet.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pet'

components:

  schemas:
    Pet:
      type: object
      properties:
        resourceType:
          type: string
```

**Comment by adamaltman** [comment] 2022-02-23 13:54
Thank you. This is a duplicate of #568

**Closed** 2022-03-09 15:25 UTC
Labels: feature request
