### ISSUE TITLE
Crash with "cannot read property ‘enum’ of null." in some cases

### ISSUE THREAD

**Issue by RomanHotsiy** [Redocly/openapi-cli#195] opened 2020-09-03 20:36 UTC
**Describe the bug**

```
Something went wrong when processing spec.yaml:

  - Cannot read property ‘enum’ of null.
```

**To Reproduce**
We have to figure it out, spotted in our prod logs.

**Expected behavior**
No crash.

**Logs**

```
npx @redocly/openapi-cli@latest lint spec.yaml --extends minimal --format json

validating spec.yaml...
Something went wrong when processing spec.yaml:

  - Cannot read property 'enum' of null.


TypeError: Cannot read property 'enum' of null
    at Schema (/tmp/openapi-cli/latest/dist/bundle.js:2:187024)
    at R (/tmp/openapi-cli/latest/dist/bundle.js:2:145849)
    at e (/tmp/openapi-cli/latest/dist/bundle.js:2:144484)
    at e (/tmp/openapi-cli/latest/dist/bundle.js:2:145102)
    at e (/tmp/openapi-cli/latest/dist/bundle.js:2:145102)
    at e (/tmp/openapi-cli/latest/dist/bundle.js:2:145102)
    at e (/tmp/openapi-cli/latest/dist/bundle.js:2:145102)
    at e (/tmp/openapi-cli/latest/dist/bundle.js:2:145102)
    at e (/tmp/openapi-cli/latest/dist/bundle.js:2:145102)
    at Object.t.walkDocument (/tmp/openapi-cli/latest/dist/bundle.js:2:146805)
```

**OpenAPI definition**
n/a

**Version(s)**
1.0.0-beta.11

**Comment by knidarkness** [comment] 2020-09-07 11:56
I am working on this issue and already discovered the root cause. Expected time to fix - 1-2 days.

**Comment by Marshevskyy** [comment] 2021-02-25 12:00
we reverted the fix for this issue in this PR: https://github.com/Redocly/openapi-cli/pull/256
due to issue https://github.com/Redocly/openapi-cli/issues/252

**Closed** 2021-06-25 11:32 UTC
Labels: Priority: Medium, Type: Bug
