### ISSUE TITLE
Add linter rules for undefined required fields

### ISSUE THREAD

**Issue by Herrick19** [Redocly/openapi-cli#660] opened 2022-04-27 01:59 UTC
Hi,

I would like to suggest an improvement.

If a property is marked as required but it doesn't exist, no error is thrown in linter.

It would be nice if it did.

Here is an example:

```
"example": {
                "description": "Example",
                "required": [
                    "foo",
                    "bar"
                ],
                "type": "object",
                "properties": {
                    "foo": {
                        "type": "string"
                    }
                }
            },
```

As you can see, "foo" and "bar" are required, but only "foo" is defined. An error should be thrown by the linter.

Thanks in advance

**Comment by RomanHotsiy** [comment] 2022-04-27 04:58
Thanks for opening an issue. I believe this is a duplicate of https://github.com/Redocly/openapi-cli/issues/477

**Closed by RomanHotsiy** 2022-04-27 04:58 UTC
