### ISSUE TITLE
Description from joined yamls not added to the output yaml

### ISSUE THREAD

**Issue by vpopescu** [Redocly/openapi-cli#500] opened 2022-01-07 19:24 UTC
**Describe the bug**
I hope I  have this right, someone correct me if I'm wrong. If I join a couple of YAMLs and they have this info definition:

```
info:
  title: Sample API 1
  description: Description for api 1
  version: '0.1'
```

shouldn't the "description" be added to the resulting tag?

**To Reproduce**

Input files:

1.yml
```yaml
openapi: 3.0.0
info:
  title: Sample API 1
  description: Description for api 1
  version: "0.1"
paths:
  /a/users:
    get:
      summary: Returns a list of users 1.
      description: Optional extended description in CommonMark or HTML.
      responses:
        '200':    # status code
          description: A JSON array of user names
          content:
            application/json:
              schema: 
                type: array
                items: 
                  type: string
```

2.yml
```yaml
openapi: 3.0.0
info:
  title: Sample API 2
  description: Description for api 2
  version: "0.1"
paths:
  /b/users:
    get:
      summary: Returns a list of users 2.
      description: Optional extended description in CommonMark or HTML 2
      responses:
        '200':    # status code
          description: A JSON array of user names
          content:
            application/json:
              schema: 
                type: array
                items: 
                  type: string
```

3.yml
```yaml
openapi: 3.0.0
info:
  title: Sample API 3
  description: Description for api 3
  version: "0.1"
paths:
  /c/users:
    get:
      summary: Returns a list of users 3.
      description: Optional extended description in CommonMark or HTML.
      responses:
        '200':    # status code
          description: A JSON array of user names
          content:
            application/json:
              schema: 
                type: array
                items: 
                  type: string

```

RESULT
```yaml
openapi: 3.0.0
info:
  title: Sample API 1
  description: Description for api 1
  version: '0.1'
paths:
  /a/users:
    get:
      summary: Returns a list of users 1.
      description: Optional extended description in CommonMark or HTML.
      responses:
        '200':
          description: A JSON array of user names
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
      tags:
        - 1_other
  /b/users:
    get:
      summary: Returns a list of users 2.
      description: Optional extended description in CommonMark or HTML 2
      responses:
        '200':
          description: A JSON array of user names
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
      tags:
        - 2_other
  /c/users:
    get:
      summary: Returns a list of users 3.
      description: Optional extended description in CommonMark or HTML.
      responses:
        '200':
          description: A JSON array of user names
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
      tags:
        - 3_other
tags:
  - name: 1_other
    x-displayName: other
  - name: 2_other
    x-displayName: other
  - name: 3_other
    x-displayName: other
x-tagGroups:
  - name: '1'
    tags:
      - 1_other
  - name: '2'
    tags:
      - 2_other
  - name: '3'
    tags:
      - 3_other
components: {}
```

**Expected behavior**
If my undrstanding is correct, I expect tags to be:

```yaml
tags:
  - name: 1_other
    description: Description for api 1
    x-displayName: other
  - name: 2_other
    x-displayName: other
     description: Description for api 2
  - name: 3_other
    x-displayName: other
    description: Description for api 3
```

**OpenAPI definition**
Added to steps to reproduce

**`openapi-cli` Version(s)**
```
$ openapi --version
1.0.0-beta.78
```

**`Node.js` Version(s)**
```
$ node -v
v14.17.1
```

**Comment by tatomyr** [comment] 2022-03-29 12:54
It looks like this is the expected behaviour. As per [documentation](https://redocly.com/docs/cli/commands/join/#array-of-paths) an entry should contain the `tags` section to produce the `info.description` in the `x-tagGroups` of the resulting file. Also, the `tags` section is not expected to contain a description. 
I'm closing the issue. Feel free to reopen it if I've missed something.

**Closed by tatomyr** 2022-03-29 12:54 UTC
