### ISSUE TITLE
Implicit 'name' and 'in' properties in 3.1-style reusable headers causes lint errors

### ISSUE THREAD

**Issue by shabbyrobe** [Redocly/openapi-cli#444] opened 2021-11-09 02:35 UTC
Based on my reading of the OpenAPI 3.1.0 spec, it looks like openapi-cli doesn't correctly handle when headers are defined in `/components/headers` and referenced in a response. 

<details>
<summary>Click here for reproducing openapi.yml file</summary>

```yaml
openapi: 3.1.0

info:
  title: Bug
  version: 0.0.1
  description: "Bug"
  license:
    name: Unlicensed
    identifier: UNLICENSED
    url: http://invalid

servers:
- description: "yep"
  url: http://invalid

components:
  headers:
    Foo-Bar:
      required: true
      description: "Foo bar!"
      schema:
        type: "string"

paths:
  /test:
    get:
      operationId: getTest
      summary: Get Test! Foo! Etc!

      parameters:
      - $ref: "#/components/headers/Foo-Bar"

      responses:
        200:
          description: "200"
          content:
            application/json:
              schema: { type: "object" }
        400:
          description: "400"
          content:
            application/json:
              schema: { type: "object" }
```
</details>

I get the following errors:

```
[1] tmp/oasbug.yml:19:7 at #/components/headers/Foo-Bar/in
Property `in` is not expected here.

[2] tmp/oasbug.yml:20:7 at #/components/headers/Foo-Bar/name
Property `name` is not expected here.
```

According to the spec about header objects (referenced in the [components property table](https://spec.openapis.org/oas/v3.1.0#fixed-fields-5)), header objects aren't supposed to contain a `name` or an `in`, as both are implied from their presence in /components/headers.

From https://spec.openapis.org/oas/v3.1.0#header-object:

> The Header Object follows the structure of the Parameter Object with the following changes:
>
>    1. name MUST NOT be specified, it is given in the corresponding headers map.
>    2. in MUST NOT be specified, it is implicitly in header.

I've tried adding `in:` and `name:` to the shared header, but that causes errors too. I also tried attaching an `in:` and a `name:` to the object containing the `$ref`, but that doesn't silence the errors either.

**Expected behavior**
I'm not 100% sure my reading is right, but I would expect no errors for the above spec (modulo any typos I may have let sneak in there of course)

**OpenAPI definition**
OpenAPI 3.1

**`openapi-cli` Version(s)**
1.0.0-beta.67

**`Node.js` Version(s)**
16.10.0

**Comment by RomanHotsiy** [comment] 2021-11-09 06:02
@shabbyrobe I can't reproduce the exact issue with the  openapi file you provided... I get different error:

```
[1] test.yaml:18:5 at #/components/headers/Foo-Bar

The field `name` must be present on this level.

16 | components:
17 |   headers:
18 |     Foo-Bar:
19 |       required: true
20 |       description: "Foo bar!"

Error was generated by the spec rule.


[2] test.yaml:18:5 at #/components/headers/Foo-Bar

The field `in` must be present on this level.

16 | components:
17 |   headers:
18 |     Foo-Bar:
19 |       required: true
20 |       description: "Foo bar!"

Error was generated by the spec rule.
```

which is 100% expected as you're trying to use Header in parameters section...

Headers in OpenAPI 3.1 should be used in response headers only.

![image](https://user-images.githubusercontent.com/3975738/140870798-29554e8c-76e3-4156-a118-0aa2a1c17142.png)

If you want to document request headers you have to use Parameters.

![image](https://user-images.githubusercontent.com/3975738/140870893-713ba780-624b-437d-b265-4338c74b515d.png)


<details>
<summary> Click here for valid openapi.yml file </summary>

```yaml
openapi: 3.1.0

info:
  title: Bug
  version: 0.0.1
  description: "Bug"
  license:
    name: Unlicensed
    identifier: UNLICENSED
    url: http://invalid

servers:
- description: "yep"
  url: http://invalid

components:
  headers:
    Foo-Bar:
      required: true
      description: "Foo bar!"
      schema:
        type: "string"
  parameters:
    Foo-Bar:
      in: header
      name: Foo-Bar
      required: true
      description: "Foo bar!"
      schema:
        type: "string"

paths:
  /test:
    get:
      operationId: getTest
      summary: Get Test! Foo! Etc!

      parameters:
      - $ref: "#/components/parameters/Foo-Bar"

      responses:
        200:
          description: "200"
          headers:
            Foo-Bar:
              $ref: "#/components/headers/Foo-Bar"
          content:
            application/json:
              schema: { type: "object" }
        400:
          description: "400"
          content:
            application/json:
              schema: { type: "object" }
```

</details>

Closing the issue. Feel free to continue converstation.

**Closed by RomanHotsiy** 2021-11-09 06:02 UTC

**Comment by shabbyrobe** [comment] 2021-11-09 22:55
Ah yep that makes sense, I missed that "reusable headers" means "reusable response headers". I've switched to using a "reusable header parameter" as you suggest and it lints fine now. The non-reproducible error was because I pasted the wrong output 🤦‍♂️. Thanks for the help, much appreciated!
